include("model_setup.jl")
include("optimization.jl")
include("../plots/GMDpaper/jointPDF_Nd.jl")
include("../plots/GMDpaper/profiles_v3.jl")
include("../plots/GMDpaper/GMD_diagnostics_tables.jl")
include("../plots/GMDpaper/sedimentary_source_profiles.jl")